<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>minco_processor</name>
  <version>0.1.0</version>
  <description>Pure C++ MINCO trajectory optimization and ESDF query library for NavDP.</description>
  <maintainer email="15207309998@163.com">alioth</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>cmake</buildtool_depend>
  <depend>eigen</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
